name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        name: Check
        steps:
            - uses: actions/checkout@v3
            - name: cargo check
              run: cargo check
    test:
        runs-on: ubuntu-latest
        name: Test
        steps:
            - uses: actions/checkout@v3
            - name: cargo test
              run: cargo test test_part
